apt install rake
apt install sqlite3
apt install ruby-dev
apt install sqlite-devel
apt install libsqlite3-dev
apt install ruby-dev
apt install ruby-devel
apt-get install libsqlite3-dev
apt install libsqlite-ruby1.9.1 
apt install libsqlite-ruby
apt-get install build-essential
apt-get install ruby-1.8dev